### Prerequisites

In [ ]:
%pip install pandas

In [1]:
import pandas as pd

### Reading Data Into Pandas Dataframe

In [26]:
df = pd.read_csv("source/raw_ecommerce_dataset.csv", header=0)

### Exploring Data

In [27]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [28]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [29]:
df.shape

(1000, 24)

In [30]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [31]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

### Cleaning using fillna / dropna

In [32]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [33]:
df["discount"]

0      58.0
1      35.0
2      65.0
3      52.0
4      17.0
       ...
995    50.0
996    45.0
997    50.0
998    20.0
999    31.0
Name: discount, Length: 1000, dtype: float64

In [34]:
df["discount"] = df["discount"].fillna(0.0)

In [35]:
df['what_customers_said']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
995    NaN
996    NaN
997    NaN
998    NaN
999    NaN
Name: what_customers_said, Length: 1000, dtype: object

In [36]:
df['what_customers_said'] = df['what_customers_said'].fillna('')

In [37]:
df['seller_name']

0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
            ...
995               NaN
996               NaN
997               NaN
998    Tru███m R███il
999               NaN
Name: seller_name, Length: 1000, dtype: object

In [38]:
df['seller_name'] = df['seller_name'].fillna('')

In [ ]:
df['videos'].head()

0                                ["rw-8376765_cae700"]
1                                ["rw-9136281_cae700"]
2    ["https://videos.myntassets.com/assets/videos/...
3    ["https://videos.myntassets.com/assets/videos/...
4                                                  NaN
Name: videos, dtype: object

In [42]:
df['videos'] = df['videos'].apply(lambda x: x if isinstance(x, list) else [])

In [ ]:
df['seller_information'].unique()

array([nan,
       'Pra███yat███fra█████████PVT█████████████████████-Sq██████████████████████████████████████████████████████████████████████████████████████████████████████',
       'Old███. 2███162█████████o. █████████████████████ Ra██████████████████████████████████████████',
       'E-1███103███PIP█████████ IN█████████████████████ Ra██████████████████',
       'A-5███ADA███R V█████████ De█████████████████████',
       'PVH███vin███ash█████████tdN█████████████████████Vay████████████████████████████████████████████████',
       '1A ███I H███E S█████████CH █████████████████████sht████████████',
       '21/███10 ███NS █████████4 ,█████████████████████NAT████████████████████████████████████',
       'SAI███USE███OT █████████ NA█████████████████████ra █████████',
       'F6 ███02,███umi█████████dus█████████████████████ill████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'Sho███o. ███-10█████████enu█████████████████████del█████████████████████',
       'sec███ A-███Plo█████████, I█████████████████████ca █████████████████████████████████████████████████████████████████████',
       '2ND███OOR███O 1█████████MAL█████████████████████RAM█████████████████████████████████████████████████████████████████████',
       'MIL███TAR███TAI█████████ LI█████████████████████ Sr███████████████████████████████████████████████████████████████████████████████████████████████████',
       'B-5███Roo███aga█████████al █████████████████████r p██████████████████',
       'Blo███B-1███abi█████████-24█████████████████████dab████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'VI/███ AB███ ST█████████ODE█████████████████████ RO████████████████████████████████████████████████████████████',
       'BLD███NO.███BAS█████████VAI█████████████████████TE,███████████████████████████████████████████████████████████████████████████████████████',
       'Sho███58-███Sec█████████ain█████████████████████rya████████████',
       '9/1███, S███et █████████ula█████████████████████lhi██████████████████',
       '3rd███oor███o. █████████Mai█████████████████████out███████████████████████████████████████████████████████████████████████████',
       'Gro███ Fl███, N█████████old█████████████████████rd ███████████████████████████████████████████████████',
       '870███TRE███SHE█████████, B█████████████████████hi ██████████████████',
       'Plo███o B███9-3█████████oor█████████████████████d A██████████████████████████████████████████████████████████████████████████████',
       'Fir███Flo███ 38█████████nds█████████████████████rad███████████████',
       'Plo███o- ███ 1s█████████Sui█████████████████████al ██████████████████████████████████████████',
       'F-2███RST███OOR█████████7VA█████████████████████R,D████████████████████████████████████████████████',
       '58/███15 ███AMP█████████LIP█████████████████████Tam██████████████████',
       '201███WAR███H, █████████TEL█████████████████████SSI█████████████████████████████████',
       'Sho███o. ███-41█████████i T█████████████████████San███████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'A-2███NOI███SEC█████████AUT█████████████████████Bud██████████████████████████████████████████',
       'Vil███agl███Waz█████████a G█████████████████████ha ████████████████████████████████████',
       '118███GH ███H C█████████OGE█████████████████████bur██████████████████████████████████████████████████████',
       'BAT███NDI███TDG█████████ Ha███████████████',
       'F 1███ Pr███sso█████████Kam█████████████████████tta███████████████████████████████████████',
       '10T███LOO███DU █████████ITY█████████████████████nga██████████████████████████████████████████████████████',
       '1st███oor███abi█████████02,█████████████████████nch██████████████████████████████████████████████████████',
       'Ary███ fo███ear█████████vt █████████████████████RTO█████████████████████████████████',
       '58/███ f/███shy█████████vip█████████████████████r P██████████████████',
       'DHV███lob███Pvt█████████lot█████████████████████gra███████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'Pum███por███Ind█████████d/ █████████████████████d. ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       '11t███loo███Fla█████████6, █████████████████████stu███████████████████████████████████████████████████████████████████████████',
       'Sil███Sum███, G█████████or,█████████████████████ No███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       '#41███42/███bla█████████ pa█████████████████████i H█████████████████████████████████████████████████████████████████████',
       'Kil███o. ███/ 1█████████, 1█████████████████████/ 1█████████████████████████████████████████████████████████████████████████████████',
       '3RD███OOR███Z-1█████████IPU█████████████████████, W████████████████████████████████████████████████',
       'C-1███SIT███, I█████████ AR█████████████████████tta█████████████████████',
       '402███Win███Mee█████████ Dh█████████████████████aka████████████████████████████████████████████████',
       'Plo███o.2███1 A█████████ust█████████████████████ram███████████████████████████████████████████████████████████████',
       'A-2███, T███D F█████████ -1█████████████████████8',
       '146███LAK███OWN█████████, 2█████████████████████t b███████████████',
       '1ST███OOR███D 2█████████ PL█████████████████████SAC█████████████████████████████████',
       '3rd███165███th █████████, s█████████████████████Ben███████████████████████████████████████████████████████████████████████████',
       'BEH███ KH███ AS█████████V N█████████████████████ - █████████',
       'Vil███e C███ota█████████ayr█████████████████████, R██████████████████',
       'MIA███ECO███ROU█████████4,P█████████████████████AND████████████████████████████████████████████████',
       '604███TH ███OR,█████████ITA█████████████████████AHA██████████████████',
       'Kil███5/1███ 18█████████ 22█████████████████████19 ███████████████████████████████████████████████████████████████',
       '243███244███ Pa█████████rat█████████████████████',
       'Rel███ce ███uku█████████Ltd█████████████████████ Ud████████████████████████████████████████████████',
       '45-███ FI███ FL█████████C,O█████████████████████, P██████████████████████████████',
       'GAL███O 4███ULA█████████IRE█████████████████████NEM██████████████████████████████',
       'D-2███Sec███ 06█████████uta█████████████████████ , ████████████████████████',
       'B-8███2nd███oor█████████r I█████████████████████elh█████████████████████',
       'Plo███o. ███, P█████████2Se█████████████████████ANA████████████',
       'Plo███o.1███ari█████████oun█████████████████████ta █████████████████████████████████████████████',
       'D-1███ Se███r-7█████████B. █████████████████████Bud██████████████████████████████████████████',
       'Vil███e B███a B█████████ata█████████████████████ogi████████████████████████████████████████████████',
       '10/███CHH███YA █████████ILL█████████████████████19,████████████████████████████████████',
       '357███has███, U█████████r, █████████████████████m ,██████████████████',
       'Plo███o. ███, P█████████2 S█████████████████████rya████████████████████████████████████',
       'A-4███ect███7 N█████████ , █████████████████████1',
       'B-1███1st███2nd█████████tor█████████████████████DES████████████',
       'EPI███RAN███PVT█████████ FI█████████████████████KHL████████████████████████',
       '615███hur███ate█████████,5 █████████████████████rch████████████████████████████████████',
       '9/5███SHU███H R█████████i N█████████████████████100███',
       '642███H F███R,J█████████LIS█████████████████████ugr████████████████████████',
       'A-5███ECT███64 █████████NAG█████████████████████, U███████████████████████████████████████',
       'A-2███Ind███ark█████████r, █████████████████████ 11███████████████████████████',
       'ASH███ PR███S, █████████CTO█████████████████████RJa███████████████████████████',
       '140███1, ███JAR█████████UTA█████████████████████N O████████████████████████████████████████████████',
       'Khe███ No███76/█████████il █████████████████████1, ██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       '5th███oor███he █████████ide█████████████████████, S███████████████████████████████████████████████████████████████████████████████████████████████████',
       ' GR███D F███R, █████████AGE█████████████████████AR,███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'D-8███2nd███oor█████████OR-█████████████████████ha ████████████████████████████████████████████████████████████',
       '295███dyo███iha█████████-6G█████████████████████200███',
       '75/███eer███gar█████████ Ha█████████████████████Mad█████████████████████',
       'B/2███udh███ura█████████AT █████████',
       'A-2███SEC███-83█████████TTA█████████████████████',
       'Wes███ry ███din█████████e L█████████████████████own█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'LL ███3, ███den█████████adu█████████████████████tak████████████',
       '1st███oor███ - █████████R -█████████████████████ha ████████████████████████████████████████████████████████████',
       'PLO███O-1███ 1S█████████ASE█████████████████████ONG███████████████████████████',
       'Bui███ng ███rat█████████eam█████████████████████Hot████████████████████████████████████████████████████████████████████████',
       'Cha███Lif███yle█████████. 3█████████████████████ad,████████████████████████████████████████████████████████████████████████████████████',
       'Plo███o 3███4,P█████████Sec█████████████████████onG███████████████████████████',
       'DEE███E-1███ SE█████████ NO█████████████████████oid███████████████████████████',
       'Fir███and███con█████████A 3█████████████████████IAL███████████████████████████████████████████████████████████████████████████',
       'C B███K, ███ FL█████████HEB█████████████████████MAH██████████████████',
       'D74███D F███ANE█████████Noi█████████████████████201██████',
       'Plo███o 5███ Ud█████████ Ph█████████████████████ , ██████████████████',
       '1ST███OOR███-80█████████88,█████████████████████Nag█████████████████████████████████████████████████████████',
       'GAL███O. ███2ND█████████-64█████████████████████R S█████████████████████████████████████████████████████████████████████████████████████████████',
       'C-1███ 1S███LOO█████████3No█████████████████████ 20██████',
       '207███rak███ to█████████cou█████████████████████ya ████████████████████████████████████████████████',
       'D-2███09,███CTO█████████ , █████████████████████1',
       '4th███oor███he █████████ide█████████████████████, S███████████████████████████████████████████████████████████████████████████████████████████████████',
       'KHA███ NO███/13█████████8/2█████████████████████2/3██████████████████████████████████████████████████████████████████',
       '. P███ NO███1 S█████████VT █████████████████████RHI███████████████████████████████████████████████████',
       'A-1███ 2n███LOO█████████NDU█████████████████████w d████████████████████████',
       'C-1███ Ba███ent█████████Col█████████████████████Del█████████████████████',
       '401███th ███or,█████████ala█████████████████████ Ex███████████████████████████████████████████████████████████████████████████',
       '10,███rac███ ro█████████ GU███████████████',
       'Plo███o 2███ 4t█████████ast█████████████████████rin██████████████████████████████████████████████████████████████████',
       '2nd███oor███LOT█████████hin█████████████████████RAM████████████████████████████████████',
       'PRI███DES███S P█████████MIT█████████████████████MAR███████████████████████████████████████████████████████████████████████████████████████',
       '837███1th███in,█████████k, █████████████████████u (████████████████████████████████████████████████',
       '12,███T F███R, █████████LDG█████████████████████POL███████████████████████████████████████████████████',
       '6TH███OOR███1 B█████████SHA█████████████████████AR ██████████████████████████████████████████',
       '4-B███nja███Tow█████████oin█████████████████████500███',
       '117███IND███RIA█████████ II█████████████████████HWA███████████████████████████████████████',
       '4TH███OOR███-16█████████R, █████████████████████BAZ████████████████████████████████████',
       'FIR███FLO███ 50█████████ND █████████████████████HI ██████████████████',
       '3RD███OOR███O 1█████████RD █████████████████████5/1████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'C/1███, 1███Plo█████████loc█████████████████████DES████████████',
       '219███elh███lhi█████████ELH████████████',
       'D-1███ Vi███ Vi█████████, U█████████████████████',
       '1st███oor███apa█████████,Na█████████████████████, S███████████████████████████████████████████████████',
       'Sho███0 D███Mar█████████t E█████████████████████mpu█████████████████████████████████',
       'G-6███Gro███ fl█████████-6N█████████████████████- 2██████',
       'B-1███ OK███ IN█████████ASE█████████████████████ , ███████████████',
       'G-9███SIT███RA █████████L A█████████████████████ - █████████',
       '59A███ATH███AR █████████Kol█████████████████████700██████',
       '21-███gal███har█████████l P█████████████████████sJa███████████████████████████',
       'F-6███Ary███ama█████████hi ██████████████████',
       'B-6███RO.███. 6█████████SIK█████████████████████R,J███████████████████████████',
       'no-███, G███ama█████████, b█████████████████████Sin███████████████████████████████████████████████████',
       'C 5███ RR███NEX█████████BEH█████████████████████PIT██████████████████████████████████████████',
       '46,███ini███lon█████████erJ█████████████████████020███',
       '11/███ Ka███i P█████████aro█████████████████████ - █████████',
       'Plo███o 6███4th█████████LM █████████████████████OR-████████████████████████████████████████████████████████████',
       'Sys███ or███ic █████████IZA█████████████████████4//███████████████████████████████████████████████████████████████',
       'C7 ███T N███29,█████████RLD█████████████████████NH3████████████████████████████████████████████████████████████████████████████████████████████████',
       'ROO███O.1███, C█████████9,G█████████████████████S.G██████████████████████████████████████████',
       'A 3███ Di███ Cl█████████/34█████████████████████Eas████████████████████████████████████████████████████████████████████████',
       'B-1███ BF███Pus█████████Enc█████████████████████I ,██████████████████',
       'OFF███ NO███1,2█████████ -5█████████████████████ION███████████████████████████████████████████████████',
       'Kha███ No███/25█████████ark█████████████████████ Gi██████████████████████████████████████████',
       'sho███x E███mer█████████d c█████████████████████te █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'Pur███ Un███d S█████████ate█████████████████████14 ████████████████████████████████████████████████████████████████████████████████████',
       'Par███n P███mer█████████ Pv█████████████████████Kha███████████████████████████████████████████████████████████████████████████████████████',
       'SHO███O 1███/2 █████████RIA█████████████████████ROA█████████████████████████████████████████████████████████████████████████████████',
       'INN███TIV███IFE█████████HNO█████████████████████or,█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'NEA███LOR███SEC█████████RT █████████████████████na █████████',
       'SF-███ MG███AD,█████████R, █████████████████████GAO████████████████████████████████████',
       '40A███ Ma███ Mo█████████ya █████████████████████ial███████████████████████████████████████████████████',
       'C-7███cto███80,█████████r P█████████████████████pra███████████████',
       '56,███und███Nag█████████ion█████████████████████shn█████████████████████████████████████████████████████████████████████',
       '83,███MLA███GAR█████████TAR██████████████████',
       'Met███Bra███ Li█████████ldi█████████████████████hag██████████████████████████████████████████████████████████████████████████████████████████',
       'III███ FL███ 17█████████AK █████████████████████LAC█████████████████████████████████',
       'Bui███ng ███13/█████████No █████████████████████, I████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       'GRE███ CO███Y, █████████ROA█████████████████████141██████',
       'A 2███, B███K-A█████████RK,█████████████████████Del█████████████████████████████████',
       'B-1███ Ba███Sid█████████ Fl█████████████████████lhi██████████████████',
       'B1/███, M███n C█████████ve,█████████████████████thu██████████████████████████████',
       'plo███o B███ Ga█████████ain█████████████████████k c████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████',
       '2nd███oor███O. █████████Lan█████████████████████Sta██████████████████████████████████████████',
       '204███8Na███an █████████van█████████████████████ras███████████████',
       'A29███ect███59,█████████udh█████████████████████rad███████████████',
       'A42███nd ███orO█████████str█████████████████████Del███████████████████████████████████████',
       ' Fi███ Wh███sal█████████ Li█████████████████████y N███████████████████████████████████████████████████████████████████████████',
       'Plo███o. ███1, █████████foc█████████████████████ram█████████████████████████████████████████████',
       'SEL███ITE███GIT█████████BRI█████████████████████E R█████████████████████████████████████████████',
       'LOW███GRO███ FL█████████ERT█████████████████████3, █████████████████████████████████████████████████████████████████████████████████████████████',
       '568███og ███ar █████████urg█████████████████████ugr████████████████████████',
       'Gal███No.███ to█████████to █████████████████████e B███████████████████████████████████████████████████████████████████████████████████████████████████',
       'IRI███rom███out█████████,La█████████████████████all█████████████████████████████████████████████████████████',
       'D-2███13,███cto█████████tar█████████████████████01N██████████████████████████████',
       'Hom███and███B/1█████████ Am█████████████████████hee███████████████████████████████████████████████████',
       'D-1███PHA███8B,█████████L A█████████████████████li ██████████████████',
       'Fir███Flo███ 27█████████ Ku█████████████████████Beg████████████████████████████████████████████████████████████████████████████████████████████████',
       '172███REE███AGA█████████NA,█████████████████████100██████████████████████████████',
       '123███, K███ANW█████████hne█████████████████████',
       '2 S███EY ███ VI█████████GAN█████████████████████N, █████████████████████████████████████████████████████████████████████',
       'Plo███o. ███,Se█████████,UD█████████████████████wk,█████████████████████████████████████████████████████████████████████',

In [48]:
df['seller_information'] = df['seller_information'].fillna('')

In [49]:
df['variations']

0                                             [{}]
1                                          [{},{}]
2                              [{},{},{},{},{},{}]
3                                              NaN
4      [{},{},{},{},{},{},{},{},{},{},{},{},{},{}]
                          ...
995                                            NaN
996                                            NaN
997                      [{},{},{},{},{},{},{},{}]
998                                            NaN
999                                  [{},{},{},{}]
Name: variations, Length: 1000, dtype: object

In [50]:
df['variations'] = df['variations'].apply(lambda x: x if isinstance(x, list) else [])

In [51]:
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
what_customers_said       0
seller_name               0
sizes                     0
videos                    0
seller_information        0
variations                0
best_offer                0
more_offers               0
category                  0
dtype: int64

In [52]:
df.isnull().sum().sum()

np.int64(0)

### Transformations

In [55]:
df[['product_id', 'title', 'product_description', 'rating']]

,product_id,title,product_description,rating
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7
...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8

In [62]:
df[['product_id', 'title', 'product_description', 'rating']][df.rating > 4.0].sort_values(by='rating')

,product_id,title,product_description,rating
31,18223842,max,Plus Size Non Padded Bra,4.1
37,16704504,ZINU,Women Silver-Toned Brass Cubic Zirconia Rhodiu...,4.1
944,9213113,Roadster,The Lifestyle Co Men White Printed Round Neck...,4.1
43,21867416,DressBerry,Women Boy Shorts Brief,4.1
960,19201678,Tokyo Talkies,Women Yellow Printed Extended Sleeves Slim Fit...,4.1
...,...,...,...,...
917,18537496,Bannos Swagger,Women Grey Solid Joggers,5.0
386,19008496,Calvin Klein Jeans,Women Skinny Fit High-Rise Light Fade Stretcha...,5.0
334,17647418,FOOTONS,Women Beige Comfort Sandals,5.0
52,22436508,Bruchi CLUB,Men Low-Rise Anti-Bacterial Basic Briefs,5.0
437,22110424,VASTRADO,Ethnic Motifs Printed Mandarin Collar Pure Cot...,5.0

In [67]:
df[['product_id', 'title', 'rating']][df.rating > 4.5].sort_values(by='product_id').head()

     product_id        title  rating
901     7326508         MISH     4.7
876     8365569          Nun     4.9
881     9557519        MANGO     5.0
929    10019547         XYXX     4.7
731    10349091  Monte Carlo     4.6

In [69]:
df = df.sort_values(by=['product_id', 'rating'])

### Dropping Duplicates

In [78]:
df.drop_duplicates(subset=['product_id'], inplace=True)

### Writing the Dataframe to Target Location

In [84]:
df.to_csv("target/output.csv", index=False)